import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/header";
import Footer from "../components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col h-screen justify-between py-5">
          <div className="h-[10vh] border-b-2">
            <Header />
          </div>
          <div className="h-[80vh] py-5 px-[75px]">{children}</div>
          <div className="h-[10vh] py-5">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
